<?php
/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

/**
 * In this file, the content for help popups is stored:
 *
 * Syntax for identifier: HELP_TABNAME_INPUTNAME, e.g. HELP_SHOP_CONFIG_BIDIRECTCROSS.
 * !!!The INPUTNAME is same as in lang.php for avoiding even more different Identifiers.!!!
 * In some cases, in lang.php GENERAL_ identifiers are used. In this file, always the tab name is used.
 *
 *
 * HTML Tags for markup (same as in online manual):
 * <span class='navipath_or_inputname'>...</span> for names of input fields, selectlists and Buttons, e.g. <span class='navipath_or_inputname'>Active</span>
 * <span class='userinput_or_code'>...</span> for input in input fields (also options in selectlists) and code
 * <span class='filename_filepath_or_italic'>...</span> for filenames, filepaths and other italic stuff
 * <span class='warning_or_important_hint'>...</span> for warning and important things
 * <ul> and <li> for lists
 */

$aLang =  [
'charset'                                     => 'UTF-8',
'HELP_SHOP_SYSTEM_OTHERCOUNTRYORDER'          => 'Aqui você pode definir se compras podem ser feitas em países para os quais não há custos de transporte definidos:<ul><li>Se a configuração é marcada, os usuários podem comprar: Os usuários são notificados de que estão cientes da adição posterior dos custos de envio.</li><li>Se a configuração estiver desmarcada, os usuários de países para os quais não há valores de entrega definidos não poderão realizar uma compra.</li></ul>',
'HELP_SHOP_SYSTEM_DISABLENAVBARS'             => 'Se essa configuração estiver marcada, a maioria dos elementos de navegação (da página) não serão mostrados durante o checkout. Dessa maneira os usuários não ficarão distraídos desnecessariamente durante o checkout.',
'HELP_SHOP_SYSTEM_DEFAULTIMAGEQUALITY'        => 'Configurações recomendadas são de 40-80:<br><ul><li>abaixo de 40, a compressão fica claramente visível e as imagens parecerão desfocadas.</li><li>Acima de 80 dificilmente será detectada qualquer melhoria de qualidade, mas o tamanho do arquivo aumenta exponencialmente.</li></ul><br>O valor padrão é 75.',
'HELP_SHOP_SYSTEM_LDAP'                       => 'Por favor edite o arquivo Core/oxldap.php.',
'HELP_SHOP_SYSTEM_SHOWVARIANTREVIEWS'         => 'Esta configuração afeta a forma como as avaliações das variantes são tratadas: Se a configuração estiver marcada, observações de variantes também são mostradas no produto pai (produto principal).',
'HELP_SHOP_SYSTEM_VARIANTSSELECTION'          => 'No eShop existem muitas listas para atribuir produtos, por exemplo, atribuindo produtos a descontos. Se essa configuração estiver marcada, as variantes também serão exibidas nessas listas.',
'HELP_SHOP_SYSTEM_VARIANTPARENTBUYABLE'       => 'Esta configuração afeta se produtos pai podem ser comprados:<ul><li>Se a configuração estiver marcada, os produtos pai também poderão ser comprados.</li><li>Se a configuração não estiver marcada, apenas variantes do produto pai poderão ser compradas.</li></ul>',
'HELP_SHOP_SYSTEM_VARIANTINHERITAMOUNTPRICE'  => 'Aqui você pode definir se os preços escalonados são herdados do produto pai: Se a configuração for verificada, os preços escalonados do produto pai também serão utilizados para as suas variantes.',
'HELP_SHOP_SYSTEM_ISERVERTIMESHIFT'           => 'O servidor no qual a eShop está rodando pode estar em um fuso horário diferente. Com esta configuração, a diferença de horas pode ser ajustada: Insira a quantidade de horas que devem ser adicionadas/subtraídas do horário do servidor. g. <kdb>+2</kdb> ou <kdb>-2</kdb>',
'HELP_SHOP_SYSTEM_INLINEIMGEMAIL'             => 'Se a configuração estiver marcada, as imagens nos e-mails serão enviadas juntamente com o e-mail. Se a configuração estiver desmarcada, as imagens serão baixadas pelo programa de e-mail no momento em que o e-mail for aberto.',
'HELP_SHOP_SYSTEM_UTILMODULE'                 => 'Insira aqui o seu arquivo PHP personalizado, que irá sobrescrever as funções do eShop na inicialização da loja.',
'HELP_SHOP_CACHE_ENABLED'                     => 'Se o cache de conteúdo dinâmico estiver ativo, conteúdos adicionais serão armazenados em cache para aumentar o desempenho. Desative esta configuração enquanto você fizer alterações na Loja (desenvolvendo módulos, adaptando modelos, etc).',
'HELP_SHOP_CACHE_LIFETIME'                    => 'Aqui você define quantos segundos o conteúdo em cache serão guardados no máximo antes de serem recriados. A configuração padrão é 36000 segundos.',
'HELP_SHOP_CACHE_CLASSES'                     => 'Aqui você define quais classes de exibição são armazenadas em cache.<br> Só mude essa configuração se estiver familiarizado com os mecanismos de cache!',
'HELP_SHOP_CACHE_REVERSE_PROXY_ENABLED'       => 'Ativa um cache de Proxy reverso HTTP. Nota: Não use "Cache de Conteúdo Dinâmico" ao mesmo tempo, como isso poderia desacelerar o desempenho.',
'HELP_SHOP_CACHE_LAYOUT_CACHE_AGE'            => 'Define a duração do layout da página em segundos. Isto será enviado através de cabeçalhos HTTP, especificando o valor do cabeçalho "Age" (idade).',
'HELP_SHOP_CONFIG_ORDEROPTINEMAIL'            => 'Se o duplo opt-in estiver ativo, os usuários recebem um e-mail com um link de confirmação quando se registram no boletim informativo. Somente se esse link de confirmação for utilizado, o usuário será registrado no boletim informativo (newsletter).<br>O duplo opt-in protege os usuários contra registros indesejados. Sem dupla opção, qualquer endereço de e-mail pode ser registrado no boletim informativo. Com dupla opção marcada, o proprietário do endereço de e-mail deve confirmar o registro.',
'HELP_SHOP_CONFIG_BIDIRECTCROSS'              => 'Com a venda cruzada, você pode oferecer mais produtos que correspondem a um produto: por exemplo, a um carro, pneus serão atribuídos como produto de venda cruzada, os pneus serão mostrados com o carro.<br>Se a venda cruzada bidirecional estiver ativada, ela funciona em ambas as direções: O carro também é mostrado com os pneus.',
'HELP_SHOP_CONFIG_STOCKONDEFAULTMESSAGE'      => '',
'HELP_SHOP_CONFIG_STOCKOFFDEFAULTMESSAGE'     => '',
'HELP_SHOP_CONFIG_OVERRIDEZEROABCPRICES'      => '',
'HELP_SHOP_CONFIG_SEARCHFIELDS'               => '',
'HELP_SHOP_CONFIG_SORTFIELDS'                 => '',
'HELP_SHOP_CONFIG_MUSTFILLFIELDS'             => '',
'HELP_SHOP_CONFIG_USENEGATIVESTOCK'           => '',
'HELP_SHOP_CONFIG_SETORDELETECURRENCY'        => '',
'HELP_SHOP_CONFIG_NEWARTBYINSERT'             => '',
/** @deprecated since v6.5.4 (2020-04-06); Suggest feature will be removed completely */
'HELP_SHOP_CONFIG_ALLOW_SUGGEST_ARTICLE'      => '',
/** end deprecated */
'HELP_SHOP_CONFIG_SEND_TECHNICAL_INFORMATION_TO_OXID' => '',
'HELP_SHOP_CONFIG_DELETERATINGLOGS'           => '',
'HELP_SHOP_CONFIG_DISABLEONLINEVATIDCHECK'    => '',
'HELP_SHOP_CONFIG_ALTVATIDCHECKINTERFACEWSDL' => '',
'HELP_SHOP_CONFIG_PSLOGIN'                    => '',
'HELP_SHOP_CONFIG_BASKETEXCLUDE'              => '',
'HELP_SHOP_CONFIG_BASKETRESERVATION'          => '',
'HELP_SHOP_CONFIG_BASKETRESERVATIONTIMEOUT'   => '',
'HELP_SHOP_CONFIG_INVITATION'                 => '',
'HELP_SHOP_CONFIG_POINTSFORINVITATION'        => '',
'HELP_SHOP_CONFIG_POINTSFORREGISTRATION'      => '',
// @deprecated since v6.5.1 (2019-02-07); credit card payment method will be no longer supported
'HELP_SHOP_CONFIG_ATTENTION'                  => '',
// END deprecated
'HELP_SHOP_CONFIG_SHOWTSINTERNATIONALFEESMESSAGE' => '',
'HELP_SHOP_CONFIG_SHOWTSCODMESSAGE'           => '',
'HELP_SHOP_CONFIG_DOWNLOADS'                  => '',
'HELP_SHOP_CONFIG_DOWNLOADS_PATH'             => '',
'HELP_SHOP_CONFIG_MAX_DOWNLOADS_COUNT'        => '',
'HELP_SHOP_CONFIG_LINK_EXPIRATION_TIME_UNREGISTERED' => '',
'HELP_SHOP_CONFIG_LINK_EXPIRATION_TIME'       => '',
'HELP_SHOP_CONFIG_PARCELSERVICE'              => '',
'HELP_SHOP_CONFIG_DOWNLOAD_EXPIRATION_TIME'   => '',
'HELP_SHOP_CONFIG_LOADREVIEWS'                  => '',
'HELP_SHOP_CONFIG_INCLUDE_PRODUCT_REVIEW_LINKS_IN_ORDER_EMAIL' => '',
'HELP_SHOP_MALL_MALLMODE'                     => '',
'HELP_SHOP_MALL_PRICEADDITION'                => '',
'HELP_SHOP_PERF_NEWESTARTICLES'               => '',
'HELP_SHOP_PERF_TOPSELLER'                    => '',
'HELP_SHOP_PERF_LOADFULLTREE'                 => '',
'HELP_SHOP_PERF_LOADACTION'                   => '',
'HELP_SHOP_PERF_USESELECTLISTPRICE'           => '',
'HELP_SHOP_PERF_DISBASKETSAVING'              => '',
'HELP_SHOP_PERF_LOADDELIVERY'                 => '',
'HELP_SHOP_PERF_LOADPRICE'                    => '',
'HELP_SHOP_PERF_PARSELONGDESCINSMARTY'        => '',
'HELP_SHOP_PERF_LOADSELECTLISTSINALIST'       => '',
'HELP_SHOP_PERF_CHECKIFTPLCOMPILE'            => 'If this setting is activated the eShop checks on each call if any templates were changed. If so, the output is  recalculated. Activate this setting when adapting templates, deactivate it if the eShop is live for better performance. <br>Further information can be found in the <a href="http://www.oxid-esales.com/en/resources/help-faq/eshop-manual/advices-adepting-templates" target="_blank" target="_blank">caching article in the manual</a>.',
'HELP_SHOP_PERF_CLEARCACHEONLOGOUT'           => '',
'HELP_SHOP_SEO_TITLEPREFIX'                   => '',
'HELP_SHOP_SEO_TITLESUFFIX'                   => '',
'HELP_SHOP_SEO_IDSSEPARATOR'                  => '',
'HELP_SHOP_SEO_SAFESEOPREF'                   => '',
'HELP_SHOP_SEO_RESERVEDWORDS'                 => '',
'HELP_SHOP_SEO_SKIPTAGS'                      => '',
'HELP_SHOP_SEO_LOWERCASEURLS'                 => '',
'HELP_SHOP_SEO_STATICURLS'                    => '',
'HELP_SHOP_MAIN_PRODUCTIVE'                   => 'As long as this setting is <span class="warning_or_important_hint">not</span> active, information about execution times and debug information are displayed  at the bottom of each page. These information is useful when customizing eShop.<br><span class="warning_or_important_hint">Activate this setting when the eShop is launched. Thereby only the eShop without additional information is displayed to your users.</span><br>',
'HELP_SHOP_MAIN_ACTIVE'                       => '',
'HELP_SHOP_MAIN_INFOEMAIL'                    => '',
'HELP_SHOP_MAIN_ORDEREMAIL'                   => '',
'HELP_SHOP_MAIN_OWNEREMAIL'                   => '',
'HELP_SHOP_MAIN_SMTPSERVER'                   => '',
'HELP_ARTICLE_MAIN_ALDPRICE'                  => '',
'HELP_ARTICLE_MAIN_VAT'                       => '',
'HELP_ARTICLE_EXTEND_UNITQUANTITY'            => 'With <span class="navipath_or_inputname">Quantity</span> and <span class="navipath_or_inputname">Unit</span> you can display the price per quantity unit (e. g. 1.43 EUR per liter). In <span class="navipath_or_inputname">Quantity</span>, enter the amount of the product (e. g. <span class="userinput_or_code">1.5</span>), in <span class="navipath_or_inputname">Unit</span> the according quantity unit (e. g. <span class="userinput_or_code">liter</span>). The price per quantity unit is calculated and displayed with the product.',
'HELP_ARTICLE_EXTEND_EXTURL'                  => '',
'HELP_ARTICLE_EXTEND_TPRICE'                  => '',
'HELP_ARTICLE_EXTEND_QUESTIONEMAIL'           => '',
'HELP_ARTICLE_EXTEND_NONMATERIAL'             => '',
'HELP_ARTICLE_EXTEND_FREESHIPPING'            => '',
'HELP_ARTICLE_EXTEND_BLFIXEDPRICE'            => '',
'HELP_ARTICLE_EXTEND_SKIPDISCOUNTS'           => '',
'HELP_ARTICLE_EXTEND_TEMPLATE'                => '',
'HELP_ARTICLE_EXTEND_ISCONFIGURABLE'          => '',
'HELP_ARTICLE_EXTEND_UPDATEPRICE'             => '',
'HELP_ARTICLE_EXTEND_SHOWCUSTOMAGREEMENT'     => '',
'HELP_ARTICLE_FILES_MAX_DOWNLOADS_COUNT'      => '',
'HELP_ARTICLE_FILES_LINK_EXPIRATION_TIME_UNREGISTERED' => '',
'HELP_ARTICLE_FILES_LINK_EXPIRATION_TIME'     => '',
'HELP_ARTICLE_FILES_NEW'                      => '',
'HELP_ARTICLE_FILES_DOWNLOAD_EXPIRATION_TIME' => '',
'HELP_ARTICLE_PICTURES_ICON'                  => '',
'HELP_ARTICLE_PICTURES_THUMB'                 => '',
'HELP_ARTICLE_PICTURES_PIC1'                  => '',
'HELP_ARTICLE_PICTURES_ZOOM1'                 => '',
'HELP_ARTICLE_STOCK_REMINDACTIV'              => '',
'HELP_ARTICLE_STOCK_STOCKFLAG'                => '',
'HELP_ARTICLE_IS_DOWNLOADABLE'                => '',
'HELP_ARTICLE_STOCK_REMINDAMAOUNT'            => '',
'HELP_ARTICLE_STOCK_DELIVERY'                 => '',
'HELP_ARTICLE_SEO_FIXED'                      => '',
'HELP_ARTICLE_SEO_KEYWORDS'                   => '',
'HELP_ARTICLE_SEO_DESCRIPTION'                => '',
'HELP_ARTICLE_SEO_ACTCAT'                     => '',
'HELP_ARTICLE_STOCK_STOCKTEXT'                => '',
'HELP_ARTICLE_STOCK_NOSTOCKTEXT'              => '',
'HELP_ARTICLE_STOCK_AMOUNTPRICE_AMOUNTFROM'   => '',
'HELP_ARTICLE_STOCK_AMOUNTPRICE_PRICE'        => '',
'HELP_ARTICLE_VARIANT_VARNAME'                => '',
'HELP_ATTRIBUTE_MAIN_DISPLAYINBASKET'         => '',
'HELP_CATEGORY_MAIN_HIDDEN'                   => '',
'HELP_CATEGORY_MAIN_PARENTID'                 => '',
'HELP_CATEGORY_MAIN_EXTLINK'                  => '',
'HELP_CATEGORY_MAIN_PRICEFROMTILL'            => '',
'HELP_CATEGORY_MAIN_DEFSORT'                  => '',
'HELP_CATEGORY_MAIN_SORT'                     => '',
'HELP_CATEGORY_MAIN_THUMB'                    => '',
'HELP_CATEGORY_MAIN_PROMOTION_ICON'           => '',
'HELP_CATEGORY_MAIN_SKIPDISCOUNTS'            => '',
'HELP_CATEGORY_SEO_FIXED'                     => '',
'HELP_CATEGORY_SEO_KEYWORDS'                  => '',
'HELP_CATEGORY_SEO_DESCRIPTION'               => '',
'HELP_CATEGORY_SEO_SHOWSUFFIX'                => '',
'HELP_CONTENT_MAIN_SNIPPET'                   => '',
'HELP_CONTENT_MAIN_MAINMENU'                  => '',
'HELP_CONTENT_MAIN_CATEGORY'                  => '',
'HELP_CONTENT_MAIN_MANUAL'                    => '',
'HELP_CONTENT_SEO_FIXED'                      => '',
'HELP_CONTENT_SEO_KEYWORDS'                   => '',
'HELP_CONTENT_SEO_DESCRIPTION'                => '',
'HELP_DELIVERY_MAIN_COUNTRULES'               => '',
'HELP_DELIVERY_MAIN_CONDITION'                => '',
'HELP_DELIVERY_MAIN_PRICE'                    => '',
'HELP_DELIVERY_MAIN_ORDER'                    => '',
'HELP_DELIVERY_MAIN_FINALIZE'                 => '',
'HELP_DELIVERYSET_MAIN_POS'                   => '',
'HELP_DISCOUNT_MAIN_SORT'                     => '',
'HELP_DISCOUNT_MAIN_PRICE'                    => '',
'HELP_DISCOUNT_MAIN_AMOUNT'                   => '',
'HELP_DISCOUNT_MAIN_REBATE'                   => '',
'HELP_GENERAL_SEO_ACTCAT'                     => '',
'HELP_GENERAL_SEO_FIXED'                      => '',
'HELP_GENERAL_SEO_SHOWSUFFIX'                 => '',
'HELP_GENERAL_SEO_OXKEYWORDS'                 => '',
'HELP_GENERAL_SEO_OXDESCRIPTION'              => '',
'HELP_GENIMPORT_FIRSTCOLHEADER'               => '',
'HELP_GENIMPORT_REPEATIMPORT'                 => '',
'HELP_LANGUAGE_DEFAULT'                       => '',
'HELP_LANGUAGE_ACTIVE'                        => '',
'HELP_PAYMENT_MAIN_SORT'                      => '',
'HELP_PAYMENT_MAIN_FROMBONI'                  => '',
'HELP_PAYMENT_MAIN_SELECTED'                  => '',
'HELP_PAYMENT_MAIN_AMOUNT'                    => '',
'HELP_PAYMENT_MAIN_ADDPRICE'                  => '',
'HELP_PAYMENT_MAIN_ADDSUMRULES'               => '',
'HELP_SELECTLIST_MAIN_TITLEIDENT'             => '',
'HELP_SELECTLIST_MAIN_FIELDS'                 => '',
'HELP_USER_MAIN_HASPASSWORD'                  => '',
'HELP_USER_PAYMENT_METHODS'                   => '',
'HELP_USER_EXTEND_NEWSLETTER'                 => '',
'HELP_USER_EXTEND_EMAILFAILED'                => '',
'HELP_USER_EXTEND_BONI'                       => '',
'HELP_MANUFACTURER_MAIN_ICON'                 => '',
'HELP_MANUFACTURER_SEO_FIXED'                 => '',
'HELP_MANUFACTURER_SEO_KEYWORDS'              => '',
'HELP_MANUFACTURER_SEO_DESCRIPTION'           => '',
'HELP_MANUFACTURER_SEO_SHOWSUFFIX'            => '',
'HELP_VOUCHERSERIE_MAIN_DISCOUNT'             => '',
'HELP_VOUCHERSERIE_MAIN_ALLOWSAMESERIES'      => '',
'HELP_VOUCHERSERIE_MAIN_ALLOWOTHERSERIES'     => '',
'HELP_VOUCHERSERIE_MAIN_SAMESEROTHERORDER'    => '',
'HELP_VOUCHERSERIE_MAIN_RANDOMNUM'            => '',
'HELP_VOUCHERSERIE_MAIN_VOUCHERNUM'           => '',
'HELP_VOUCHERSERIE_MAIN_CALCULATEONCE'        => '',
'HELP_WRAPPING_MAIN_PICTURE'                  => '',
'HELP_PROMOTIONS_BANNER_PICTUREANDLINK'       => '',
'HELP_SHOP_PERF_SEO_CACHE'                    => '',
'HELP_ALTERNATIVE_IMAGE_SERVER_NOTE'          => '',
'HELP_SHOP_RDFA_CONTENT_OFFERER'              => '',
'HELP_SHOP_RDFA_CONTENT_PAYMENT'              => '',
'HELP_SHOP_RDFA_CONTENT_DELIVERY'             => '',
'HELP_SHOP_RDFA_VAT'                          => '',
'HELP_SHOP_RDFA_DURATION_PRICES'              => '',
'HELP_SHOP_RDFA_LOGO_URL'                     => '',
'HELP_SHOP_RDFA_GEO_LONGITUDE'                => '',
'HELP_SHOP_RDFA_GEO_LATITUDE'                 => '',
'HELP_SHOP_RDFA_GLN'                          => '',
'HELP_SHOP_RDFA_NAICS'                        => '',
'HELP_SHOP_RDFA_ISIC'                         => '',
'HELP_SHOP_RDFA_DUNS'                         => '',
'HELP_SHOP_RDFA_SHOW_PRODUCTSTOCK'            => '',
'HELP_SHOP_RDFA_RATING_MIN'                   => '',
'HELP_SHOP_RDFA_RATING_MAX'                   => '',
'HELP_SHOP_RDFA_COND'                         => '',
'HELP_SHOP_RDFA_FNC'                          => '',
'HELP_SHOP_RDFA_COSTUMER'                     => '',
'HELP_SHOP_RDFA_DURATION_OFFERINGS'           => '',
'HELP_SHOP_PERF_SYSREQ_CHECK'                 => '',
'HELP_SHOP_CONFIG_ADDITIONAL_SERVICE_VAT_CALCULATION_BIGGEST_NET'  => '',
'HELP_SHOP_CONFIG_ADDITIONAL_SERVICE_VAT_CALCULATION_PROPORTIONAL' => '',
'HELP_SHOP_CONFIG_VIEWNETPRICE'               => '',
'HELP_SHOP_CONFIG_ENTERNETPRICE'              => '',
'HELP_REVERSE_PROXY_GET_FRONTEND'             => '',
'HELP_REVERSE_PROXY_GET_BACKEND'              => '',
'HELP_SHOP_CONFIG_DEBIT_OLD_BANK_INFORMATION_NOT_ALLOWED' => '',
'HELP_SHOP_CONFIG_ENABLE_INTANGIBLE_PRODUCTS_AGREEMENT'   => '',
'HELP_SHOP_CONFIG_FIELDS_CONTACTFORM'         => '',
];
