<?php
/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

/**
 * In this file, the content for help popups is stored:
 *
 * Syntax for identifier: HELP_TABNAME_INPUTNAME, e.g. HELP_SHOP_CONFIG_BIDIRECTCROSS.
 * !!!The INPUTNAME is same as in lang.php for avoiding even more different Identifiers.!!!
 * In some cases, in lang.php GENERAL_ identifiers are used. In this file, always the tab name is used.
 *
 *
 * HTML Tags for markup (same as in online manual):
 * <span class='navipath_or_inputname'>...</span> for names of input fields, selectlists and Buttons, e.g. <span class='navipath_or_inputname'>Active</span>
 * <span class='userinput_or_code'>...</span> for input in input fields (also options in selectlists) and code
 * <span class='filename_filepath_or_italic'>...</span> for filenames, filepaths and other italic stuff
 * <span class='warning_or_important_hint'>...</span> for warning and important things
 * <ul> and <li> for lists
 */

$aLang =  [
'charset'                                     => 'UTF-8',
'HELP_SHOP_SYSTEM_OTHERCOUNTRYORDER'          => 'Aqui você pode definir se compras podem ser feitas em países para os quais não há custos de transporte definidos:<ul><li>Se a configuração é marcada, os usuários podem comprar: Os usuários são notificados de que estão cientes da adição posterior dos custos de envio.</li><li>Se a configuração estiver desmarcada, os usuários de países para os quais não há valores de entrega definidos não poderão realizar uma compra.</li></ul>',
'HELP_SHOP_SYSTEM_DISABLENAVBARS'             => 'Se essa configuração estiver marcada, a maioria dos elementos de navegação (da página) não serão mostrados durante o checkout. Dessa maneira os usuários não ficarão distraídos desnecessariamente durante o checkout.',
'HELP_SHOP_SYSTEM_DEFAULTIMAGEQUALITY'        => 'Configurações recomendadas são de 40-80:<br><ul><li>abaixo de 40, a compressão fica claramente visível e as imagens parecerão desfocadas.</li><li>Acima de 80 dificilmente será detectada qualquer melhoria de qualidade, mas o tamanho do arquivo aumenta exponencialmente.</li></ul><br>O valor padrão é 75.',
'HELP_SHOP_SYSTEM_LDAP'                       => 'Por favor edite o arquivo Core/oxldap.php.',
'HELP_SHOP_SYSTEM_SHOWVARIANTREVIEWS'         => 'Esta configuração afeta a forma como as avaliações das variantes são tratadas: Se a configuração estiver marcada, observações de variantes também são mostradas no produto pai (produto principal).',
'HELP_SHOP_SYSTEM_VARIANTSSELECTION'          => 'No eShop existem muitas listas para atribuir produtos, por exemplo, atribuindo produtos a descontos. Se essa configuração estiver marcada, as variantes também serão exibidas nessas listas.',
'HELP_SHOP_SYSTEM_VARIANTPARENTBUYABLE'       => 'Esta configuração afeta se produtos pai podem ser comprados:<ul><li>Se a configuração estiver marcada, os produtos pai também poderão ser comprados.</li><li>Se a configuração não estiver marcada, apenas variantes do produto pai poderão ser compradas.</li></ul>',
'HELP_SHOP_SYSTEM_VARIANTINHERITAMOUNTPRICE'  => 'Aqui você pode definir se os preços escalonados são herdados do produto pai: Se a configuração for verificada, os preços escalonados do produto pai também serão utilizados para as suas variantes.',
'HELP_SHOP_SYSTEM_ISERVERTIMESHIFT'           => 'O servidor no qual a eShop está rodando pode estar em um fuso horário diferente. Com esta configuração, a diferença de horas pode ser ajustada: Insira a quantidade de horas que devem ser adicionadas/subtraídas do horário do servidor. g. <kdb>+2</kdb> ou <kdb>-2</kdb>',
'HELP_SHOP_SYSTEM_INLINEIMGEMAIL'             => 'Se a configuração estiver marcada, as imagens nos e-mails serão enviadas juntamente com o e-mail. Se a configuração estiver desmarcada, as imagens serão baixadas pelo programa de e-mail no momento em que o e-mail for aberto.',
'HELP_SHOP_SYSTEM_UTILMODULE'                 => 'Insira aqui o seu arquivo PHP personalizado, que irá sobrescrever as funções do eShop na inicialização da loja.',
'HELP_SHOP_CACHE_ENABLED'                     => 'Se o cache de conteúdo dinâmico estiver ativo, conteúdos adicionais serão armazenados em cache para aumentar o desempenho. Desative esta configuração enquanto você fizer alterações na Loja (desenvolvendo módulos, adaptando modelos, etc).',
'HELP_SHOP_CACHE_LIFETIME'                    => 'Aqui você define quantos segundos o conteúdo em cache serão guardados no máximo antes de serem recriados. A configuração padrão é 36000 segundos.',
'HELP_SHOP_CACHE_CLASSES'                     => 'Aqui você define quais classes de exibição são armazenadas em cache.<br> Só mude essa configuração se estiver familiarizado com os mecanismos de cache!',
'HELP_SHOP_CACHE_REVERSE_PROXY_ENABLED'       => 'Ativa um cache de Proxy reverso HTTP. Nota: Não use "Cache de Conteúdo Dinâmico" ao mesmo tempo, como isso poderia desacelerar o desempenho.',
'HELP_SHOP_CACHE_LAYOUT_CACHE_AGE'            => 'Define a duração do layout da página em segundos. Isto será enviado através de cabeçalhos HTTP, especificando o valor do cabeçalho "Age" (idade).',
'HELP_SHOP_CONFIG_ORDEROPTINEMAIL'            => 'Se o duplo opt-in estiver ativo, os usuários recebem um e-mail com um link de confirmação quando se registram no boletim informativo. Somente se esse link de confirmação for utilizado, o usuário será registrado no boletim informativo (newsletter).<br>O duplo opt-in protege os usuários contra registros indesejados. Sem dupla opção, qualquer endereço de e-mail pode ser registrado no boletim informativo. Com dupla opção marcada, o proprietário do endereço de e-mail deve confirmar o registro.',
'HELP_SHOP_CONFIG_BIDIRECTCROSS'              => 'Com a venda cruzada, você pode oferecer mais produtos que correspondem a um produto: por exemplo, a um carro, pneus serão atribuídos como produto de venda cruzada, os pneus serão mostrados com o carro.<br>Se a venda cruzada bidirecional estiver ativada, ela funciona em ambas as direções: O carro também é mostrado com os pneus.',
'HELP_SHOP_CONFIG_STOCKONDEFAULTMESSAGE'      => 'Para cada produto você pode configurar uma mensagem para quando o produto está em estoque.<br>Com essa configuração ativa uma mensagem padrão será exibida, caso nenhuma mensagem específica para um produto for inserida. A mensagem padrão <span class="filename_filepath_or_italic">Pronta para envio</span> é exibida.',
'HELP_SHOP_CONFIG_STOCKOFFDEFAULTMESSAGE'     => 'Para cada produto você pode configurar uma mensagem para quando o produto não estiver em estoque.<br>Com essa configuração ativa uma mensagem padrão será exibida, caso nenhuma mensagem específica para um produto for inserida. A mensagem padrão <span class="filename_filepath_or_italic">Este item não está em estoque e deve será pedido ao fornecedor antes </span> é mostrada.',
'HELP_SHOP_CONFIG_OVERRIDEZEROABCPRICES'      => 'Você pode configurar preços especiais para usuários específicos: Para cada produto você pode inserir preços A, B e C. Se usuários estão no grupo de usuários <span class="filename_filepath_or_italic">Preço A</span>, o preço é exibido para eles em vez do preço normal.<br>Se essa configuração estiver marcada, o preço normal do produto é usado se nenhum preço A, B ou C estiver disponível.<br>Você deve ativar essa configuração se você estiver usando os preços A, B e C: Caso contrário, 0, 0 é exibido para os usuários de acordo se nenhum preço de A, B ou C estiver definido.',
'HELP_SHOP_CONFIG_SEARCHFIELDS'               => 'Aqui você pode definir os campos do banco de dados em que a pesquisa de produto busca. Digite um campo por linha.<br>As entradas mais comuns são:<ul><li>oxtitle = Title</li><li>oxshortdesc = descrição</li><li>oxsearchchaves = termos inseridos para cada produto</li><li>oxartnum = número de produto</li></ul>',
'HELP_SHOP_CONFIG_SORTFIELDS'                 => 'Aqui você pode definir os campos do banco de dados que podem ser usados para ordenar as listas de produtos. Digite um campo por linha.<br>As escolhas mais comuns são:<ul><li>oxtitle = Título</li><li>oxprice = Preço</li><li>oxvarminprice = O preço mais baixo se forem utilizadas variantes com preços diferentes.</li><li>oxartnum = Números de produto</li><li>oxrating = Classificação dos produtos</li><li>oxstock = Estoque</li></ul>',
'HELP_SHOP_CONFIG_MUSTFILLFIELDS'             => 'Aqui você definir os campos obrigatórios para a criação de novo usuário. Insira um campo por linha.<br>Os valores mais comuns são:<ul><li>oxuser__oxfname = Nome</li><li>oxuser__oxlname = Sobrenome</li><li>oxuser__oxstreet = Endereço</li><li>oxuser__oxstreetnr = Número</li><li>oxuser__oxzip = CEP</li><li>oxuser__oxcity = Cidade</li><li>oxuser__oxcountryid = País</li><li>oxuser__oxfon = Telefone</li></ul><br>Você também pode definir os campos no caso do usuário utilizar um endereço alternativo para entrega. Os valores mais comuns são::<ul><li>oxaddress__oxfname = Nome</li><li>oxaddress__oxlname = Sobrenome</li><li>oxaddress__oxstreet = Rua</li><li>oxaddress__oxstreetnr = Número</li><li>oxaddress__oxzip = CEP</li><li>oxaddress__oxcity = Cidade</li><li>oxaddress__oxcountryid = País</li><li>oxaddress__oxfon = Telefone</li></ul>',
'HELP_SHOP_CONFIG_USENEGATIVESTOCK'           => 'Com <span class="navipath_or_inputname">Permitir valores negativos de estoque</span> você pode definir como os níveis de ações são calculados dos produtos estão fora de estoque:<br><ul><li>Se a configuração for marcada, valores de estoque negativas são calculados se outras unidades são compradas.</li><li>Se a configuração estiver desmarcada, o valor do estoque nunca cai abaixo de 0, mesmo que mais unidades sejam compradas.</li></ul>',
'HELP_SHOP_CONFIG_SETORDELETECURRENCY'        => 'Adicione ou remova as moedas. Cada linha contém parâmetros de uma moeda separados pelo símbolo @.<br /><br /><ul><li>código da moeda, de acordo com a ISO 4217 (ex. EUR)</li><li>a taxa de moeda básica para o valor 1. 0</li><li>separador decimal</li><li>separador de milhares</li><li>moeda sign</li><li>casas decimais</li><li>parâmetros opcionais "Front". Se inserido, o sinal de moeda aparece na frente do preço.</li></ul>',
'HELP_SHOP_CONFIG_NEWARTBYINSERT'             => 'Na página inicial do seu eShop, os produtos mais recentes são exibidos em <span class="filename_filepath_or_italic">Acabaram de chegar!</span>. Esta configuração determina como os produtos mais novos são calculados: por data de criação ou pela data da última mudança em administração/última ordem.',
/** @deprecated since v6.5.4 (2020-04-06); Suggest feature will be removed completely */
'HELP_SHOP_CONFIG_ALLOW_SUGGEST_ARTICLE'      => 'Ativar recomendação de produtos nas páginas de detalhes do produto.',
/** end deprecated */
'HELP_SHOP_CONFIG_SEND_TECHNICAL_INFORMATION_TO_OXID' => 'Nenhuma informação relevante do negócio ou informações do cliente serão transmitidas. Os dados recolhidos exclusivamente se aplicam às informações tecnológicas. Melhorar a qualidade dos nossos produtos informações como essa serão coletadas:<ul>  <li>número de instalações da Comunidade de eShop OXID em todo o mundo</li>  <li>número médio de extensões instaladas por OXID eShop</li>  <li>extensões de maior spread para a OXID eShop</li></ul>',
'HELP_SHOP_CONFIG_DELETERATINGLOGS'           => 'Se os usuários avaliarem um produto, eles não podem avaliar o produto novamente. Aqui você pode definir após quantos dias os usuários podem avaliar um produto novamente. Deixe em branco para desativar - os produtos podem ser avaliados apenas uma vez por usuário.',
'HELP_SHOP_CONFIG_DISABLEONLINEVATIDCHECK'    => 'A verificação de CPF/CNPJ é executada se um cliente de um país estrangeiro dentro da UE entrar em um CPF/CNPJ durante o pedido. Se o CPF/CNPJ é válido, nenhum imposto é calculado para esse pedido.<br>Se a verificação estiver desativada, o IVA normal para o país de destino é sempre calculado.',
'HELP_SHOP_CONFIG_ALTVATIDCHECKINTERFACEWSDL' => 'Aqui você pode digitar uma URL alternativa para a verificação de ID de IVA online.',
'HELP_SHOP_CONFIG_PSLOGIN'                    => 'O Login Privado transforma loja regular em uma loja exclusiva para membros da loja. Isso ajuda a desenvolver comunidades de clientes com interesses semelhantes. Isto restringe o acesso a todas as páginas da eShop.',
'HELP_SHOP_CONFIG_BASKETEXCLUDE'              => 'Permite inserir produtos apenas de uma categoria (raiz), se uma alteração da categoria for detectada o usuário será solicitado a finalizar o pedido (vá para o checkout) ou continue a comprar (o carrinho é esvaziado neste caso). Usando este recurso em conjunto com uma estrutura de categoria devidamente organizada, você pode implementar carrinhos divididos para diferentes fornecedores.',
'HELP_SHOP_CONFIG_BASKETRESERVATION'          => 'Quando desativar esta opção a eShop reduz o estoque do produto exatamente no momento em que o pedido é confirmado pelo cliente e o check-out é finalizado.<br><br> Com esta opção ativada esta funcionalidade altera-se desta forma: O estoque do produto é reduzido e está sendo <b>reservado</b> quando o produto é colocado no carrinho. A reserva é cancelada quando o conteúdo do carrinho é comprado ou o carrinho expira.',
'HELP_SHOP_CONFIG_BASKETRESERVATIONTIMEOUT'   => 'Após este limite de tempo os produtos reservados serão devolvidos para o estoque e o carrinho do cliente é esvaziado.',
'HELP_SHOP_CONFIG_INVITATION'                 => 'O convite é usado para sugerir seus amigos para o site e obter pontos de crédito pelo convite.',
'HELP_SHOP_CONFIG_POINTSFORINVITATION'        => 'A quantidade de pontos creditados ao usuário obtém quando ele foi convidado por usuário já registrado. O usuário convidado deve se registrar para obter esses pontos. Pontos de crédito obtidos são armazenados no perfil de usuário e podem ser usados pelo proprietário da loja para qualquer propósito.',
'HELP_SHOP_CONFIG_POINTSFORREGISTRATION'      => 'A quantidade de pontos creditados ao usuário que convidou alguém para a loja. Usuário obtém pontos de crédito apenas se o usuário convidado registra na loja. Pontos de crédito obtidos são armazenados no perfil de usuário e podem ser usados pelo proprietário da loja para qualquer propósito.',
// @deprecated since v6.5.1 (2019-02-07); credit card payment method will be no longer supported
'HELP_SHOP_CONFIG_ATTENTION'                  => 'Cuidado: mesmo que a criptografia seja usada, contratos do Cartão de Crédito geralmente proíbem isto de forma rigorosa!',
// END deprecated
'HELP_SHOP_CONFIG_SHOWTSINTERNATIONALFEESMESSAGE' => 'No quarto passo do processo de check-out, a página CMS "oxtsinternationalfees" é exibida adicionalmente.',
'HELP_SHOP_CONFIG_SHOWTSCODMESSAGE'           => 'No quarto passo do processo de check-out, a página "oxtscodmessage" é exibida adicionalmente.',
'HELP_SHOP_CONFIG_DOWNLOADS'                  => 'Loja com produtos para download. Ative aqui que os produtos podem ser pedidos e baixados.',
'HELP_SHOP_CONFIG_DOWNLOADS_PATH'             => 'Caminho onde os arquivos de produtos para download são armazenados.',
'HELP_SHOP_CONFIG_MAX_DOWNLOADS_COUNT'        => 'Aqui você pode definir quantas vezes o usuário pode baixar no mesmo link após pedido. Esta é a configuração padrão para todos os produtos. Você pode mudar este valor para cada arquivo de produto em Administrar Produtos -> Produtos -> Downloads.',
'HELP_SHOP_CONFIG_LINK_EXPIRATION_TIME_UNREGISTERED' => 'Aqui você pode definir quantas vezes o usuário pode baixar no mesmo link, se o usuário encomendou sem registro. Esta é a configuração padrão para todos os produtos. Você pode mudar este valor para cada arquivo de produto em Administrar Produtos -> Produtos -> Downloads.',
'HELP_SHOP_CONFIG_LINK_EXPIRATION_TIME'       => 'Especifique o tempo em horas, em que o link de download é válido após a compra. Esta é a configuração padrão para todos os produtos. ou pode mudar este valor para cada arquivo de produto em Administrar Produtos -> Produtos -> Downloads.',
'HELP_SHOP_CONFIG_PARCELSERVICE'              => 'Preencha o URL de rastreamento do seu fornecedor. <i>##ID##</i> é um espaço reservado e será substituído pelo número de rastreamento respectivo.',
'HELP_SHOP_CONFIG_DOWNLOAD_EXPIRATION_TIME'   => 'Especifique o tempo em horas, em que o link de download é válido após o primeiro download. Esta é a configuração padrão para todos os produtos. ou pode mudar este valor para cada arquivo de produto em Administrar Produtos -> Produtos -> Downloads.',
'HELP_SHOP_CONFIG_LOADREVIEWS'                  => 'Os usuários podem rever e classificar seus produtos com estrelas. Se essa configuração estiver marcada, as avaliações de revisões/estrelas existentes serão carregadas e exibidas com o produto. Esta configuração pode diminuir o desempenho da loja.',
'HELP_SHOP_CONFIG_INCLUDE_PRODUCT_REVIEW_LINKS_IN_ORDER_EMAIL' => 'Por favor, verifique novamente se isto é compatível com as leis aplicáveis. Esta configuração só será aplicada, se "usuários revisões e classificações por estrela" estiver ativada.',
'HELP_SHOP_MALL_MALLMODE'                     => 'Aqui você pode definir o que é mostrado como página inicial desta loja:<ul><li><span class="navipath_or_inputname">Mostrar seletor de lojas</span>: Uma página onde as diferentes lojas que podem ser selecionadas é mostrada.</li><li><span class="navipath_or_inputname">Mostrar a primeira página da loja</span>: A página inicial normal desta Loja é mostrada.</li></ul>',
'HELP_SHOP_MALL_PRICEADDITION'                => 'Você pode definir uma sobretaxa sobre todos os preços de produtos nesta loja: Insira a sobretaxa e selecione se é uma porcentagem (<span class="userinput_or_code">%</span>) ou um valor absoluto (<span class="userinput_or_code">abs</span>).',
'HELP_SHOP_PERF_NEWESTARTICLES'               => 'Uma lista dos produtos mais novos é exibida em <span class="filename_filepath_or_italic">Chegou agora!</span>. Aqui você pode definir como a lista é gerada:<ul><li><span class="userinput_or_code">inativo</span>: A lista não é mostrada.</li><li>manual<span class="userinput_or_code"></span>: Você pode definir os produtos <span class="navipath_or_inputname">Informação do Cliente -> Promoções -></span> na promoção <span class="filename_filepath_or_italic">Acabou de chegar!</span>.</li><li><span class="userinput_or_code">automáticos</span>: Os produtos são calculados automaticamente.</li></ul>',
'HELP_SHOP_PERF_TOPSELLER'                    => 'Uma lista de produtos mais vendidos é exibida no <span class="filename_filepath_or_italic">Topo da loja</span>. Aqui você pode definir como a lista é gerada:<ul><li><span class="userinput_or_code">inativa</span>: A lista n é mostrada.</li><li><span class="userinput_or_code">manual</span>: Você pode definir os produtos<span class="navipath_or_inputname">Informações ao Cliente -> Promoções -></span> em Promoção<span class="filename_filepath_or_italic">Mais vendidos</span>.</li><li><span class="userinput_or_code">automatic</span>: Os produtos são selecionados automaticamente.</li></ul>',
'HELP_SHOP_PERF_LOADFULLTREE'                 => 'Se esta configuração estiver marcada, a árvore de categorias inteira é exibida na navegação de categoria (todas as categorias são expandidas). Isto só funciona se a navegação por categoria não for exibida no topo.',
'HELP_SHOP_PERF_LOADACTION'                   => 'Se esta configuração estiver marcada, promoções como <span class="filename_filepath_or_italic">acabaram de chegar!</span> e <span class="filename_filepath_or_italic">Mais vendidos</span> são carregadas e mostradas.',
'HELP_SHOP_PERF_USESELECTLISTPRICE'           => 'Nas listas de seleções podem ser configurados sobretaxas/descontos. Se essa configuração estiver marcada, as sobretaxas/descontos serão carregados e aplicados. Se não estiver selecionado, as sobrecargas/descontos não serão aplicadas.',
'HELP_SHOP_PERF_DISBASKETSAVING'              => 'O carrinho de compras dos usuários registrados é salvo. Quando eles visitam a sua Loja, o conteúdo do carrinho de compras é carregado. Se você ativar esta configuração, os carrinhos de compras não serão mais salvos.',
'HELP_SHOP_PERF_LOADDELIVERY'                 => 'Se você desativar esta configuração, nenhum custo de envio será calculado: Os custos de envio são sempre 0,00 EUR.',
'HELP_SHOP_PERF_LOADPRICE'                    => 'Se você desativar esta configuração, nenhum preço de produto será calculado: nenhum preço será exibido.',
'HELP_SHOP_PERF_PARSELONGDESCINSMARTY'        => 'Se essa configuração estiver ativa, as descrições dos produtos e categorias serão analisadas através do Smarty: Você pode usar as tags Smarty (e. g. para usar variáveis) <br>',
'HELP_SHOP_PERF_LOADSELECTLISTSINALIST'       => 'Normalmente listas de seleção são mostradas apenas na exibição de detalhes de um produto. Se você ativar essa configuração, as listas de seleção também são mostradas nas listas de produtos (por exemplo, resultados da pesquisa, categorias).',
'HELP_SHOP_PERF_CHECKIFTPLCOMPILE'            => 'If this setting is activated the eShop checks on each call if any templates were changed. If so, the output is  recalculated. Activate this setting when adapting templates, deactivate it if the eShop is live for better performance. <br>Further information can be found in the <a href="http://www.oxid-esales.com/en/resources/help-faq/eshop-manual/advices-adepting-templates" target="_blank" target="_blank">caching article in the manual</a>.',
'HELP_SHOP_PERF_CLEARCACHEONLOGOUT'           => 'Normalmente, o cache todo é esvaziado assim que você salvar qualquer alteração no administrador da eShop. Isso pode causar problemas de desempenho no administrador. Se esta configuração estiver ativada, o cache só será esvaziado quando você sair do administrador da Loja.',
'HELP_SHOP_SEO_TITLEPREFIX'                   => 'Cada página tem um título. Este título é exibido na barra superior da janela do navegador. Com <span class="navipath_or_inputname">Prefixo para título</span> e <span class="navipath_or_inputname">Sufixo para título</span> você pode preencher o texto antes e depois dos títulos:<br><ul><li>No <span class="navipath_or_inputname">Prefixo para título</span>, digite o texto a ser exibido na frente do título.</li></ul>',
'HELP_SHOP_SEO_TITLESUFFIX'                   => 'Cada página tem um título. Este título é exibido na barra superior da janela do navegador. Com <span class="navipath_or_inputname">Prefixo do título</span> e <span class="navipath_or_inputname">Sufixo do título</span>, você pode preencher o texto antes e depois dos títulos da página:<br><ul><li>No <span class="navipath_or_inputname">Sufixo do título</span> digite o texto a ser exibido atrás do título.</li></ul>',
'HELP_SHOP_SEO_IDSSEPARATOR'                  => 'O separador é usado se nomes de categorias e nomes de produtos consistirem em várias palavras. O separador é usado ao invés de espaços, exemplo: www.sualoja.com/categoria-nome-com-muitas-palavras<br>Se nenhum separador for inserido, - é usado.',
'HELP_SHOP_SEO_SAFESEOPREF'                   => 'Se vários produtos tiverem o mesmo nome e estiverem na mesma categoria, obterão a mesma URL de SEO. Para evitar isso, o Sufixo de SEO está anexado. Se não for definido Sufixo do SEO <span class="filename_filepath_or_italic">oxid</span> é usado.',
'HELP_SHOP_SEO_RESERVEDWORDS'                 => 'Algumas URLs são definidas na Loja, como www.sualoja.com/admin para acessar o administrador da Loja. Se uma categoria foi nomeada <span class="filename_filepath_or_italic">admin</span> a URL do SEO seria www. oureshop.com/admin também - a categoria não pôde ser acessada. Portanto, o sufixo SEO está anexado a estas URLs. Você pode definir aqui quais URLs são sufixadas automaticamente.',
'HELP_SHOP_SEO_SKIPTAGS'                      => 'Se nenhuma tag META for definida para produtos e categorias, as tags META serão criadas automaticamente. Assim, é possível omitir palavras muito comuns; todas as palavras inseridas aqui são omitidas ao criar as tags META.',
'HELP_SHOP_SEO_LOWERCASEURLS'                 => 'Minúscula todos os caracteres maiúsculos em URLs de SEO. Por exemplo, www.sualoja.com/Kiteboarding/Kites/ transforma em www.sualoja.com/kiteboarding/kites/.',
'HELP_SHOP_SEO_STATICURLS'                    => 'Para páginas especiais (ex. termos gerais e condições) você pode inserir URLs de SEO fixas. Ao selecionar uma URL estática, a URL normal é mostrada na <span class="navipath_or_inputname">URL Padrão</span>. Nos campos de entrada abaixo, você pode definir uma URL de SEO para cada idioma.',
'HELP_SHOP_MAIN_PRODUCTIVE'                   => 'O modo eShop não produtivo destina-se à instalação da eShop, configuração, personalização dos \'templates\' e \'debug\' de módulos. Assim que o modo produtivo for ativado <span class="warning_or_important_hint">ligado</span>, o tratamento de cache e o comportamento de relatar erros são otimizados para a loja ao vivo.<br><span class="warning_or_important_hint">Ative esta configuração quando a eShop for lançada.</span><br>Encontre outras informações importantes para entrar ao vivo com o OXID eShop em nossa <a href="https://oxidforge.org/en/check-before-going-live.html" target="_blank">OXIDforge</a>.',
'HELP_SHOP_MAIN_ACTIVE'                       => 'Com o valor <span class="navipath_or_inputname">Ativo</span> você pode ativar/desativar toda a Loja. Se a Loja estiver desativada, uma mensagem dizendo que a eShop está temporariamente offline será exibida aos usuários. Isto pode ser útil para manutenção.',
'HELP_SHOP_MAIN_INFOEMAIL'                    => 'Todos os e-mails enviados através da página de contato são enviados para este endereço de e-mail.',
'HELP_SHOP_MAIN_ORDEREMAIL'                   => 'Quando os usuários recebem um e-mail com um resumo do pedido. Respostas para este e-mail são enviadas para <span class="navipath_or_inputname">respostas ao e-mail de pedido</span>.',
'HELP_SHOP_MAIN_OWNEREMAIL'                   => 'Quando o pedido dos usuários você recebe um e-mail com um resumo do pedido. Estes e-mails serão enviados para <span class="navipath_or_inputname">e-mails de pedidos</span>.',
'HELP_SHOP_MAIN_SMTPSERVER'                   => 'Dados SMTP são necessários para o envio de e-mails (por exemplo, enviando aos clientes um e-mail de confirmação de pedido).',
'HELP_ARTICLE_MAIN_ALDPRICE'                  => 'Com <span class="navipath_or_inputname">Preços Especiais</span> você pode configurar preços especiais para certos usuários (grupos de usuários "Preço A", "Preço B" e "Preço C").',
'HELP_ARTICLE_MAIN_VAT'                       => 'Aqui você pode inserir uma taxa especial para este produto. Este imposto é usado para este produto em todos os cálculos posteriores (carrinho, pedido, fatura)',
'HELP_ARTICLE_EXTEND_UNITQUANTITY'            => 'Com <span class="navipath_or_inputname">Quantidade</span> e <span class="navipath_or_inputname">Unidade</span> você pode definir o preço por quantidade de umaunidade de medida. O preço por unidade de quantidade é calculado e exibido com o produto (exemplo: 1,43 EUR por litro). Em <span class="navipath_or_inputname">Quantidade</span>, digite o valor do produto (por exemplo, <span class="userinput_or_code">1.</span>), em <span class="navipath_or_inputname">Unidade</span> defina a unidade de quantidade correspondente (por exemplo, <span class="userinput_or_code">litro</span>). Você pode escolher o tipo de unidade de valores determinados ou, selecionando o tipo de unidade em branco "-", insira o tipo de unidade manualmente. Se você deseja adicionar uma lista de tipos existente, por favor siga este <a href="https://oxidforge.org/en/adding-new-unit-types.html" target="_blank">link</a> para instruções.',
'HELP_ARTICLE_EXTEND_EXTURL'                  => 'Em <span class="navipath_or_inputname">URL externa</span> você pode inserir um link onde informações adicionais sobre o produto estão disponíveis (por exemplo, no site do fabricante). No <span class="navipath_or_inputname">texto para URL externa</span> você pode inserir o texto que está vinculado, eexmplo: <span class="userinput_or_code">Informações adicionais sobre o website do fabricante</span>.',
'HELP_ARTICLE_EXTEND_TPRICE'                  => 'Em <span class="navipath_or_inputname">RRP</span> você pode inserir o preço de varejo recomendado do fabricante. Se você entrar no RRP, ele será exibido para os usuários: Acima do preço do produto <span class="filename_filepath_or_italic">Reduzido de RRP Agora somente</span> será exibido.',
'HELP_ARTICLE_EXTEND_QUESTIONEMAIL'           => 'Em <span class="navipath_or_inputname">Contato Alternativo</span> você pode inserir um endereço de e-mail. Se os usuários enviarem perguntas sobre este produto, ele será enviado para este endereço de e-mail. Se nenhum endereço de e-mail for inserido, a consulta será enviada para o endereço de e-mail normal.',
'HELP_ARTICLE_EXTEND_NONMATERIAL'             => 'A configuração é herdada do produto pai para variantes e aplica-se a todo o produto.',
'HELP_ARTICLE_EXTEND_FREESHIPPING'            => 'A configuração é herdada do produto pai para variantes e aplica-se a todo o produto.',
'HELP_ARTICLE_EXTEND_BLFIXEDPRICE'            => 'O preço desejado pode ser desativado para este produto.',
'HELP_ARTICLE_EXTEND_SKIPDISCOUNTS'           => 'Se <span class="navipath_or_inputname">ignorar todos os descontos negativos</span> estiver ativo, os direitos negativos não serão calculados para este produto. Estes incluem descontos e cupoms.',
'HELP_ARTICLE_EXTEND_TEMPLATE'                => 'A visão detalhada de um produto pode ser exibida com um \'template\' diferente. Para fazer isso, insira o caminho e o nome do template a ser usado.',
'HELP_ARTICLE_EXTEND_ISCONFIGURABLE'          => 'Se o produto é personalizável, um campo adicional é exibido na página de detalhes do produto e no carrinho de compras. Aqui os clientes podem inserir texto para personalizar o produto.<br><br>Um exemplo típico são camisetas que podem ser impressas com texto personalizado. No campo de entrada, os clientes podem inserir o texto que será impresso na camiseta.',
'HELP_ARTICLE_EXTEND_UPDATEPRICE'             => 'Os preços podem ser alterados em um momento definido. Os campos fornecidos atualizam os preços padrão. Se você deixar os valores de preço "0", os preços não serão atualizados.',
'HELP_ARTICLE_EXTEND_SHOWCUSTOMAGREEMENT'     => 'Se esta opção estiver ativada, os usuários terão que confirmar os termos e condições no quarto passo do processo de check-out para este item específico. Certifique-se de que a opção geral também está ativada e que o item do produto é intangível ou baixável.',
'HELP_ARTICLE_FILES_MAX_DOWNLOADS_COUNT'      => 'Aqui você pode definir quantas vezes o usuário pode baixar no mesmo link após o pedido. Para este arquivo você pode substituir a configuração padrão, que foi definida em Configurações Master -> Configurações Core -> Configurações -> Downloads para todos os produtos.',
'HELP_ARTICLE_FILES_LINK_EXPIRATION_TIME_UNREGISTERED' => 'Aqui você pode definir quantas vezes o usuário pode baixar no mesmo link, se o usuário encomendou sem registro. Para este arquivo você pode substituir a configuração padrão, que foi definida em Configurações Master -> Configurações Core -> Configurações -> Downloads para todos os produtos.',
'HELP_ARTICLE_FILES_LINK_EXPIRATION_TIME'     => 'Especifique o tempo em horas, em que o link de download é válido após o pedido. Para este arquivo você pode substituir a configuração padrão, que foi definida em Configurações Master -> Configurações Core -> Configurações -> Downloads para todos os produtos.',
'HELP_ARTICLE_FILES_NEW'                      => 'Digite o nome de um arquivo via FTP transferido ou envie um novo arquivo aqui. Note que arquivos grandes devem ser carregados via FTP. Limitação de tamanho do arquivo é válida apenas quando o arquivo é carregado via administrador. Esta limitação depende das configurações do PHP do servidor e pode ser editada apenas lá.',
'HELP_ARTICLE_FILES_DOWNLOAD_EXPIRATION_TIME' => 'Especifique o tempo em horas, em que o link de download é válido após o primeiro download. Para este arquivo você pode substituir a configuração padrão, que foi definida em Configurações Master -> Configurações Core -> Configurações -> Downloads para todos os produtos.',
'HELP_ARTICLE_PICTURES_ICON'                  => 'Ícones são as menores fotos de um produto. Por exemplo, eles são usados no carrinho de compras.<br>Ao fazer upload de um ícone personalizado você irá substituir o ícone gerado a partir da primeira imagem do produto.<br>Após o upload, o nome do arquivo é exibido no Ícone. Se nenhum ícone for enviado --- será exibido.',
'HELP_ARTICLE_PICTURES_THUMB'                 => '',
'HELP_ARTICLE_PICTURES_PIC1'                  => '',
'HELP_ARTICLE_PICTURES_ZOOM1'                 => '',
'HELP_ARTICLE_STOCK_REMINDACTIV'              => 'A configuração é herdada do produto pai para variantes e aplica-se a todo o produto.',
'HELP_ARTICLE_STOCK_STOCKFLAG'                => '',
'HELP_ARTICLE_IS_DOWNLOADABLE'                => '',
'HELP_ARTICLE_STOCK_REMINDAMAOUNT'            => '',
'HELP_ARTICLE_STOCK_DELIVERY'                 => '',
'HELP_ARTICLE_SEO_FIXED'                      => '',
'HELP_ARTICLE_SEO_KEYWORDS'                   => '',
'HELP_ARTICLE_SEO_DESCRIPTION'                => '',
'HELP_ARTICLE_SEO_ACTCAT'                     => '',
'HELP_ARTICLE_STOCK_STOCKTEXT'                => '',
'HELP_ARTICLE_STOCK_NOSTOCKTEXT'              => '',
'HELP_ARTICLE_STOCK_AMOUNTPRICE_AMOUNTFROM'   => '',
'HELP_ARTICLE_STOCK_AMOUNTPRICE_PRICE'        => '',
'HELP_ARTICLE_VARIANT_VARNAME'                => '',
'HELP_ATTRIBUTE_MAIN_DISPLAYINBASKET'         => '',
'HELP_CATEGORY_MAIN_HIDDEN'                   => '',
'HELP_CATEGORY_MAIN_PARENTID'                 => '',
'HELP_CATEGORY_MAIN_EXTLINK'                  => '',
'HELP_CATEGORY_MAIN_PRICEFROMTILL'            => '',
'HELP_CATEGORY_MAIN_DEFSORT'                  => '',
'HELP_CATEGORY_MAIN_SORT'                     => '',
'HELP_CATEGORY_MAIN_THUMB'                    => '',
'HELP_CATEGORY_MAIN_PROMOTION_ICON'           => '',
'HELP_CATEGORY_MAIN_SKIPDISCOUNTS'            => '',
'HELP_CATEGORY_SEO_FIXED'                     => '',
'HELP_CATEGORY_SEO_KEYWORDS'                  => '',
'HELP_CATEGORY_SEO_DESCRIPTION'               => '',
'HELP_CATEGORY_SEO_SHOWSUFFIX'                => '',
'HELP_CONTENT_MAIN_SNIPPET'                   => '',
'HELP_CONTENT_MAIN_MAINMENU'                  => '',
'HELP_CONTENT_MAIN_CATEGORY'                  => '',
'HELP_CONTENT_MAIN_MANUAL'                    => '',
'HELP_CONTENT_SEO_FIXED'                      => '',
'HELP_CONTENT_SEO_KEYWORDS'                   => '',
'HELP_CONTENT_SEO_DESCRIPTION'                => '',
'HELP_DELIVERY_MAIN_COUNTRULES'               => '',
'HELP_DELIVERY_MAIN_CONDITION'                => '',
'HELP_DELIVERY_MAIN_PRICE'                    => '',
'HELP_DELIVERY_MAIN_ORDER'                    => '',
'HELP_DELIVERY_MAIN_FINALIZE'                 => '',
'HELP_DELIVERYSET_MAIN_POS'                   => '',
'HELP_DISCOUNT_MAIN_SORT'                     => '',
'HELP_DISCOUNT_MAIN_PRICE'                    => '',
'HELP_DISCOUNT_MAIN_AMOUNT'                   => '',
'HELP_DISCOUNT_MAIN_REBATE'                   => '',
'HELP_GENERAL_SEO_ACTCAT'                     => '',
'HELP_GENERAL_SEO_FIXED'                      => '',
'HELP_GENERAL_SEO_SHOWSUFFIX'                 => '',
'HELP_GENERAL_SEO_OXKEYWORDS'                 => '',
'HELP_GENERAL_SEO_OXDESCRIPTION'              => '',
'HELP_GENIMPORT_FIRSTCOLHEADER'               => '',
'HELP_GENIMPORT_REPEATIMPORT'                 => '',
'HELP_LANGUAGE_DEFAULT'                       => '',
'HELP_LANGUAGE_ACTIVE'                        => '',
'HELP_PAYMENT_MAIN_SORT'                      => '',
'HELP_PAYMENT_MAIN_FROMBONI'                  => '',
'HELP_PAYMENT_MAIN_SELECTED'                  => '',
'HELP_PAYMENT_MAIN_AMOUNT'                    => '',
'HELP_PAYMENT_MAIN_ADDPRICE'                  => '',
'HELP_PAYMENT_MAIN_ADDSUMRULES'               => '',
'HELP_SELECTLIST_MAIN_TITLEIDENT'             => '',
'HELP_SELECTLIST_MAIN_FIELDS'                 => '',
'HELP_USER_MAIN_HASPASSWORD'                  => '',
'HELP_USER_PAYMENT_METHODS'                   => '',
'HELP_USER_EXTEND_NEWSLETTER'                 => '',
'HELP_USER_EXTEND_EMAILFAILED'                => '',
'HELP_USER_EXTEND_BONI'                       => '',
'HELP_MANUFACTURER_MAIN_ICON'                 => '',
'HELP_MANUFACTURER_SEO_FIXED'                 => '',
'HELP_MANUFACTURER_SEO_KEYWORDS'              => '',
'HELP_MANUFACTURER_SEO_DESCRIPTION'           => '',
'HELP_MANUFACTURER_SEO_SHOWSUFFIX'            => '',
'HELP_VOUCHERSERIE_MAIN_DISCOUNT'             => '',
'HELP_VOUCHERSERIE_MAIN_ALLOWSAMESERIES'      => '',
'HELP_VOUCHERSERIE_MAIN_ALLOWOTHERSERIES'     => '',
'HELP_VOUCHERSERIE_MAIN_SAMESEROTHERORDER'    => '',
'HELP_VOUCHERSERIE_MAIN_RANDOMNUM'            => '',
'HELP_VOUCHERSERIE_MAIN_VOUCHERNUM'           => '',
'HELP_VOUCHERSERIE_MAIN_CALCULATEONCE'        => '',
'HELP_WRAPPING_MAIN_PICTURE'                  => '',
'HELP_PROMOTIONS_BANNER_PICTUREANDLINK'       => '',
'HELP_SHOP_PERF_SEO_CACHE'                    => '',
'HELP_ALTERNATIVE_IMAGE_SERVER_NOTE'          => '',
'HELP_SHOP_RDFA_CONTENT_OFFERER'              => '',
'HELP_SHOP_RDFA_CONTENT_PAYMENT'              => '',
'HELP_SHOP_RDFA_CONTENT_DELIVERY'             => '',
'HELP_SHOP_RDFA_VAT'                          => '',
'HELP_SHOP_RDFA_DURATION_PRICES'              => '',
'HELP_SHOP_RDFA_LOGO_URL'                     => '',
'HELP_SHOP_RDFA_GEO_LONGITUDE'                => '',
'HELP_SHOP_RDFA_GEO_LATITUDE'                 => '',
'HELP_SHOP_RDFA_GLN'                          => '',
'HELP_SHOP_RDFA_NAICS'                        => '',
'HELP_SHOP_RDFA_ISIC'                         => '',
'HELP_SHOP_RDFA_DUNS'                         => '',
'HELP_SHOP_RDFA_SHOW_PRODUCTSTOCK'            => '',
'HELP_SHOP_RDFA_RATING_MIN'                   => '',
'HELP_SHOP_RDFA_RATING_MAX'                   => '',
'HELP_SHOP_RDFA_COND'                         => '',
'HELP_SHOP_RDFA_FNC'                          => '',
'HELP_SHOP_RDFA_COSTUMER'                     => '',
'HELP_SHOP_RDFA_DURATION_OFFERINGS'           => '',
'HELP_SHOP_PERF_SYSREQ_CHECK'                 => '',
'HELP_SHOP_CONFIG_ADDITIONAL_SERVICE_VAT_CALCULATION_BIGGEST_NET'  => '',
'HELP_SHOP_CONFIG_ADDITIONAL_SERVICE_VAT_CALCULATION_PROPORTIONAL' => '',
'HELP_SHOP_CONFIG_VIEWNETPRICE'               => '',
'HELP_SHOP_CONFIG_ENTERNETPRICE'              => '',
'HELP_REVERSE_PROXY_GET_FRONTEND'             => '',
'HELP_REVERSE_PROXY_GET_BACKEND'              => '',
'HELP_SHOP_CONFIG_DEBIT_OLD_BANK_INFORMATION_NOT_ALLOWED' => '',
'HELP_SHOP_CONFIG_ENABLE_INTANGIBLE_PRODUCTS_AGREEMENT'   => '',
'HELP_SHOP_CONFIG_FIELDS_CONTACTFORM'         => '',
];
