<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "English";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset' => '',

    'TCKLARNA_KLARNAMAINMENU'      => '',
    'TCKLARNA_START'               => '',
    'TCKLARNA_GENERAL_SETTINGS'    => '',
    'TCKLARNA_CONFIGURATION'       => '',
    'TCKLARNA_CONFIGURATION_KCO'   => '',
    'TCKLARNA_CONFIGURATION_KP'    => '',
    'TCKLARNA_KLARNADESIGN'        => '',
    'TCKLARNA_EXTERNAL_PAYMENTS'   => '',
    'TCKLARNA_EXTRA_MERCHANT_DATA' => '',
    'TCKLARNA_BASIC_SETTINGS'      => '',
    'TCKLARNA_DISCOUNT_TITLE'      => 'Rabatt',

    'tcklarna_tbclklarna_orders'     => '',
    'TCKLARNA_NO_OPTIONS_MODE'       => '',
    'TCKLARNA_CHANGES_SAVED'         => '',
    'TCKLARNA_EMPTY_FIELDS_WARRNING' => '',

    'TCKLARNA_EASY'                         => '',
    'TCKLARNA_PHONE'                        => 'Telefon',
    'TCKLARNA_EMAIL'                        => '',
    'TCKLARNA_BUSINESS_HOURS'               => '',
    'TCKLARNA_MONDAY'                       => '',
    'TCKLARNA_TUESDAY'                      => '',
    'TCKLARNA_WEDNESDAY'                    => '',
    'TCKLARNA_THURSDAY'                     => '',
    'TCKLARNA_FRIDAY'                       => '',
    'TCKLARNA_SATURDAY'                     => '',
    'TCKLARNA_SUNDAY'                       => '',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'  => '',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'   => '',
    'TCKLARNA_COUNTRY'                      => 'Land',
    'TCKLARNA_MERCHANT_ID'                  => '',
    'TCKLARNA_PASSWORD'                     => 'Lösenord',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'         => '',
    'TCKLARNA_ENABLE_LOGGING'               => '',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA' => '',
    'TCKLARNA_PRODUCT_URLS'                 => '',
    'TCKLARNA_IMAGE_URLS'                   => '',
    'TCKLARNA_ENABLE_ANONYMIZATION'         => '',
    'TCKLARNA_ADD'                          => '',

    'TCKLARNA_CHECKOUT_NAME'             => '',
    'TCKLARNA_PAYMENTS_NAME'             => '',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE' => '',

    'TCKLARNA_CHECKOUT_DESC' => '',

    'TCKLARNA_PAYMENTS_DESC' => '',

    'TCKLARNA_EASY_AND_SECURE_SHOPPING' => '',
    'TCKLARNA_WELCOME_TO_CONFIGURATION' => '',

    'TCKLARNA_CREATE_USER_ACCOUNT'               => '',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'           => '',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE' => '',
    'TCKLARNA_NO_CHECKBOX'                       => '',

    'TCKLARNA_DISPLAY_ON_HOME'        => '',
    'TCKLARNA_BANNER_SRC'             => '',
    'TCKLARNA_FOOTER'                 => '',
    'TCKLARNA_DISPLAY_IN_FOOTER'      => '',
    'TCKLARNA_FOOTER_PAYMENT_METHODS' => '',
    'TCKLARNA_FOOTER_KLARNA_LOGO'     => '',
    'TCKLARNA_DESIGN'                 => '',
    'TCKLARNA_LONG_VERSION'           => '',
    'TCKLARNA_SHORT_VERSION'          => '',
    'TCKLARNA_WHITE'                  => '',
    'TCKLARNA_BLACK'                  => '',
    'TCKLARNA_DETAILS_AND_BASKET'     => '',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET' => '',
    'TCKLARNA_ON_PROD_PAGE'           => '',
    'TCKLARNA_ON_BASKET_PAGE'         => '',
    'TCKLARNA_DISPLAY_BUY_NOW'        => '',
    'TCKLARNA_PAYMENT_DESIGN'         => '',
    'TCKLARNA_CHECKOUT_DESIGN'        => '',
    'TCKLARNA_COLOR_SETTINGS'         => '',
    'TCKLARNA_BORDER'                 => '',
    'TCKLARNA_BORDER_SELECTED'        => '',
    'TCKLARNA_BUTTON'                 => '',
    'TCKLARNA_BUTTON_TEXT'            => '',
    'TCKLARNA_CHECKBOX'               => '',
    'TCKLARNA_CHECKBOX_CHECKMARK'     => '',
    'TCKLARNA_DETAILS'                => '',
    'TCKLARNA_HEADER'                 => '',
    'TCKLARNA_LINK'                   => '',
    'TCKLARNA_TEXT'                   => '',
    'TCKLARNA_SECONDARY_TEXT'         => '',
    'TCKLARNA_RADIUS_SETTINGS'        => '',
    'TCKLARNA_BORDER_RADIUS'          => '',

    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'   => '',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'            => '',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'           => '',
    'TCKLARNA_ENABLE_AUTOFOCUS'                  => '',
    'TCKLARNA_ADD_A_CUSTOM_CHECKBOX'             => '',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'            => '',
    'TCKLARNA_ENABLE_PRE_FILLING'                => '',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'       => '',
    'TCKLARNA_SALUTATION_MANDATORY'              => '',
    'TCKLARNA_SET_TAC_URI'                       => '',
    'TCKLARNA_SET_CANCEL_URI'                    => '',
    'TCKLARNA_SHIPPING_DETAILS'                  => '',
    'TCKLARNA_NO_VALIDATION_NEEDED'              => '',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED' => '',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'      => '',
    'TCKLARNA_ORDER_VALIDATION'                  => '',

    'TCKLARNA_CHOOSE_KP_OPTIONS' => '',
    'TCKLARNA_PAY_LATER'         => '',
    'TCKLARNA_PAY_LATER.'        => '',
    'TCKLARNA_PAY_LATER_START'   => '',
    'TCKLARNA_PAY_LATER_TEXT'    => '',
    'TCKLARNA_SLICE_IT'          => '',
    'TCKLARNA_SLICE_IT.'         => '',
    'TCKLARNA_SLICE_IT_START'    => '',
    'TCKLARNA_SLICE_IT_TEXT'     => '',
    'TCKLARNA_PAY_NOW'           => '',
    'TCKLARNA_PAY_NOW.'          => '',
    'TCKLARNA_PAY_NOW_START'     => '',
    'TCKLARNA_PAY_NOW_TEXT'      => '',
    'TCKLARNA_CHECKOUT'          => '',
    'TCKLARNA_CHECKOUT_START'    => '',

    'TCKLARNA_EXTERNAL_PAYMENTS_ADMIN_DESC'   =>
        '',
    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC' => '',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'     => '',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'    => '',
    'TCKLARNA_CONFIGURATION_KCO_ADMIN_DESC'   => '',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'    => '',

    'TCKLARNA_PAYMENT_METHOD'          => 'Betalsätt',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD' => '',
    'TCKLARNA_EXTERNAL_CHECKOUT'       => '',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'   => '',
    'TCKLARNA_IMAGE_URI_EXT_CHECKOUT'  => '',
    'TCKLARNA_IMAGE_TIP_69x24'         => '',
    'TCKLARNA_IMAGE_TIP_276x48'        => '',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'  => '',

    'TCKLARNA_CHOOSE' => 'välja',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO' => '',
    'TCKLARNA_PAYMENT_HISTORY_FULL'  => '',
    'TCKLARNA_PASSTHROUGH_FIELD'     => '',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'           => '',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY' => '',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                => '',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'               => '',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'               => '',
    'TCKLARNA_OTHER_PAYMENT'                        => '',
    'TCKLARNA_DIRECT_BANKING'                       => '',
    'TCKLARNA_CARD'                                 => '',

    'TCKLARNA_TEST_MODE_TOOLTIP'                       => '',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'              => '',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                 => '',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'    => '',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP' => '',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'    => '',
    'TCKLARNA_DEFAULT_COUNTRY_TOOLTIP'                 => '',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                  => '',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'               => '',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'             => '',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'            => '',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP' => '',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                 => '',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'            => '',
    'TCKLARNA_ENABLE_AUTOFOCUS_TOOLTIP'                => '',
    'TCKLARNA_CHECKBOX_TOOLTIP'                        => '',
    'TCKLARNA_VALIDATION_TOOLTIP'                      => '',
    'TCKLARNA_SALUTATION_MANDATORY_TOOLTIP'            => '',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'         => '',
    'TCKLARNA_ENABLE_PRE_FILLING_TOOLTIP'              => '',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION_TOOLTIP'     => '',
    'TCKLARNA_TERMS_AND_CONDITIONS_URL_TOOLTIP'        => '',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'         => '',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                => '',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'    => '',
    'TCKLARNA_ENABLE_EXTERNAL_PAYMENT_TOOLTIP'         => '',
    'TCKLARNA_ENABLE_EXTERNAL_CHECKOUT_TOOLTIP'        => '',
    'TCKLARNA_EXTERNAL_PAYMENT_IMAGE_URL_TOOLTIP'      => '',
    'TCKLARNA_EXTERNAL_CHECKOUT_IMAGE_URL_TOOLTIP'     => '',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                => '',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'              => '',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'               => '',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'        => '',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                => '',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                => '',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'           => '',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                 => '',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                      => '',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'          => '',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'              => '',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'            => '',
    'TCKLARNA_BORDER_TOOLTIP'                          => '',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                 => '',
    'TCKLARNA_BUTTON_TOOLTIP'                          => '',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                     => '',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                 => '',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'       => '',
    'TCKLARNA_DETAILS_TOOLTIP'                         => '',
    'TCKLARNA_HEADER_TOOLTIP'                          => '',
    'TCKLARNA_LINK_TOOLTIP'                            => '',
    'TCKLARNA_TEXT_TOOLTIP'                            => '',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                  => '',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                   => '',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'               => '',
    'KLARNA_CAPTURE_FULL_ORDER'                    => '',
    'KLARNA_CAPTURE_ID'                            => '',
    'KLARNA_CAPTURE_REFERENCE'                     => '',
    'KLARNA_CAPTURE_AMOUNT'                        => '',
    'KLARNA_CAPTURE_DATE'                          => '',
    'KLARNA_REFUND_AMOUNT'                         => '',
    'KLARNA_REFUND_DESCRIPTION'                    => '',
    'KLARNA_REFUND_DATE'                           => '',
    'KLARNA_CAPTURES'                              => '',
    'KLARNA_REFUNDS'                               => '',
    'KLARNA_CANCEL_ORDER'                          => '',
    'KLARNA_ORDER_IS_CANCELLED'                    => '',
    'KLARNA_SEE_ORDER_IN_PORTAL'                   => '',
    'KLARNA_ORDER_NOT_IN_SYNC'                     => '',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'               => '',
    'TCKLARNA_KP_INVOICE_MSG'                      => '',
    'TCKLARNA_KCO_INVOICE_MSG'                     => '',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA' => '',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'     => '',
    'KLARNA_UNAUTHORIZED_REQUEST'                  => '',
    'KLARNA_ORDER_NOT_FOUND'                       => '',
    'TCKLARNA_PRODUCT_NAME'                        => '',
    'TCKLARNA_ANONYMIZED_PRODUCT'                  => '',
    'TCKLARNA_VOUCHER_DISCOUNT'                    => '',

    'TCKLARNA_KCO_BUTTON_TOOLTIP'                    => '',
    'TCKLARNA_KCO_BUTTON_TEXT_TOOLTIP'               => '',
    'TCKLARNA_KCO_DESIGN_CHECKBOX_TOOLTIP'           => '',
    'TCKLARNA_KCO_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP' => '',
    'TCKLARNA_KCO_HEADER_TOOLTIP'                    => '',
    'TCKLARNA_KCO_LINK_TOOLTIP'                      => '',
    'TCKLARNA_KCO_BORDER_RADIUS_TOOLTIP'             => '',

    'TCKLARNA_GIFT_WRAPPING_TITLE' => 'Presentförpacking',
    'TCKLARNA_GIFT_CARD_TITLE'     => '',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED' => '',
    'TCKLARNA_ERROR_WRONG_CREDS'             => '',
    'TCKLARNA_ERROR_KCO_INACTIVE'            => '',

    'KLARNA_CAPTURE_SUCCESSFULL'            => '',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED' => '',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'     => '',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'   => '',
    'TCKLARNA_USER_GUIDE'                   => '',
    'TCKLARNA_REGISTER_NOW_BUTTON'          => '',
    'TCKLARNA_LEARN_MORE_BUTTON'            => '',

    'TCKLARNA_CUSTOMER_TYPE'         => '',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP' => '',
    'TCKLARNA_B2C'                   => '',
    'TCKLARNA_B2B'                   => '',
    'TCKLARNA_B2BOTH'                => '',
    'TCKLARNA_NEED_SUPPORT'          => '',
    'TCKLARNA_REACH_SUPPORT'         => '',

    'TCKLARNA_EU_WARNING' => '',
    'TCKLARNA_ON_SITE_MESSAGING' => '',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC' => '',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'         => '',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'         => '',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'          => '',
    'TCKLARNA_TOP_STRIP_PROMOTION'              => '',
    'TCKLARNA_FOOTER_PROMOTION'                 => '',
    'TCKLARNA_BANNER_PROMOTION'                 => '',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP' => '',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP' => '',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'  => '',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'      => '',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'         => '',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'         => '',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'   => '',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC' => '',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2' => '',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON' => '',
    'TCKLARNA_INSTANT_SHOPPING_MENU' => '',
    'TCKLARNA_INSTANT_SHOPPING_HEADER' => '',
    'TCKLARNA_IS_ENABLED_HEADLINE' => '',
    'TCKLARNA_IS_ENABLED' => '',
    'TCKLARNA_IS_BUTTON_REPLACE' => '',
    'TCKLARNA_IS_REPLACE' => '',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP' => '',
    'TCKLARNA_IS_ENABLED_TOOLTIP' => '',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE' => '',
    'TCKLARNA_IS_VARIATION_TOOLTIP' => '',
    'TCKLARNA_IS_TAGLINE_TOOLTIP' => '',
    'TCKLARNA_IS_TYPE_TOOLTIP' => '',
    'TCKLARNA_IS_BUTTON_PREVIEW' => '',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS' => '',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP' => '',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET' => '',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP' => '',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE' => '',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS' => '',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP' => '',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY' => '',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP' => '',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY' => '',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP' => '',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION' => '',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE' => '',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE' => 'Typ',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY' => '',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP' => '',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'            => '',
    'TCKLARNA_IS_TERMS_URI_TIP' => '',
);